version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    command: npm run dev:frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:5173
    command: npm run dev:backend 