[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 